### PR TITLE
Refactor Module: edit  files

### PR DESCRIPTION
**Pull request by mfreitassm**
Hey Guys,
 I've just merged rds modules and implement random passwords with SSM.

### CODE REVIEW

**Review by zarajoy — DISMISSED** [review]
nice updates

**Review by alanlima — DISMISSED** [review]
Well done @mfreitassm 
Thanks for the changes

**Review by alanlima — APPROVED** [review]
Hey @mfreitassm,
I need to make some changes due to recent updates in the main repo.
I added the outputs.tf file to export the SSM parameters for ECS module.

**Review by mfreitassm — COMMENTED** [review]
Okay! @alanlima

**Pull request merged**
